# Generated by Django 6.0.6 on 2026-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
