# Generated by Django 6.0.6 on 2026-06-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_department_alter_user_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(0, 'student'), (1, 'moderator'), (2, 'admin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verfied',
            field=models.BooleanField(choices=[('not-verified', 'Not Verfied'), ('pending', 'Pending'), ('verified', 'Verified')], null=True),
        ),
    ]
