# Generated by Django 6.0.6 on 2026-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role_alter_user_is_verfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(0, 'student'), (1, 'moderator'), (2, 'admin')], default='student', max_length=10, null=True),
        ),
    ]
