# Generated by Django 6.0.6 on 2026-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.CharField(choices=[('not-verified', 'Not Verfied'), ('pending', 'Pending'), ('verified', 'Verified')], default='not-verified', max_length=20),
        ),
    ]
